name: attendy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  provider: ^4.0.0
  intl: ^0.17.0
  http: ^0.13.3
  image_picker: ^0.8.1+1
  firebase_storage: ^3.1.5
  shared_preferences: ^2.0.6
  local_auth: ^1.1.6
  cupertino_icons: ^1.0.0
  google_maps_flutter: ^2.0.3
  location: ^4.1.1
  geolocator: ^7.0.3
  fluttertoast: ^8.0.7
  flutter_polyline_points: ^1.0.0
  syncfusion_flutter_pdf: ^19.2.44-beta
  universal_html: ^1.2.4
  path_provider: ^2.0.1
  open_file: ^3.1.0
  rename: ^1.3.1
  android_alarm_manager: ^2.0.2
  flutter_launcher_icons: ^0.9.0
  flutter_phone_direct_caller: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700